### ISSUE TITLE
URISyntaxException error using urlcleaner

### ISSUE THREAD

**Issue by salimk** [shekhargulati/urlcleaner#2]
Hi i try to use your API like this , i got the following  error coud your help ?  
Thank you in advance 
import com.shekhargulati.urlcleaner.UrlCleaner;
in my code i import also net.URL
import java.net.URL;

 String xx=UrlCleaner.normalizeUrl("http://shekhargulati.com/%7Eabout/");
System.out.println(xx);
--->
com.shekhargulati.urlcleaner.UrlCleanerException: java.net.URISyntaxException: Relative path in absolute URI: http://shekhargulati.com%5C~about
    at com.shekhargulati.urlcleaner.UrlCleaner.normalizeUrl(UrlCleaner.java:62)
    at com.shekhargulati.urlcleaner.UrlCleaner.normalizeUrl(UrlCleaner.java:73)
Caused by: java.net.URISyntaxException: Relative path in absolute URI: http://shekhargulati.com%5C~about
    at java.net.URI.checkPath(URI.java:1823)
    at java.net.URI.<init>(URI.java:672)
    at com.shekhargulati.urlcleaner.UrlCleaner.normalizeUrl(UrlCleaner.java:59)

**Comment by vaibhav26sharma** [comment]
@salimk  You are getting this error because you are using single '/' before '%'. 
Replacing the link with **http://shekhargulati.com//%7Eabout//** should solve this problem but then it is leading to some other error.

**Comment by salimk** [comment]
thank you for your help
